language: swift
script: xcodebuild -project Example/Example.xcodeproj -scheme Example -destination platform\=iOS\ Simulator,name\=iPhone\ 6 build test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGN_ENTITLEMENTS="" CODE_SIGNING_ALLOWED=NO TRAVIS=1 | xcpretty && exit ${PIPESTATUS[0]}
xcode_destination: iOS Simulator,name=iPhone 6
osx_image: xcode11.4
